
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models
{
    public class BEG_COB_JURIDICO
    {

        [NotMapped]
        public string Trigger_BEG_TRG_BI_COB_JURIDIDO_APEX { get; set; } = `{"triggering_event":"INSERT","trigger_body":"declare\n  --\n  VB_APEX boolean;\n  --\nbegin\n  if :new.APP_USER is not null\n     and INSERTING then\n    --  :new.DOCSTATUS := 'CO';\n    VB_APEX       := BEG_PCK_APEX.BEG_FNC_COMPIERE_APEX_TABLE(:new.APP_USER,\n                                                              'BEG_COB_JURIDICO',\n                                                              :new.AD_CLIENT_ID,\n                                                              :new.AD_ORG_ID,\n                                                              :new.CREATED,\n                                                              :new.CREATEDBY,\n                                                              :new.UPDATED,\n                                                              :new.UPDATEDBY,\n                                                              :new.BEG_COB_JURIDICO_ID);\n    :new.APP_USER := null;\n  end if;\nend BEG_TRG_BI_COB_JURIDIDO_APEX;\n"}`;
    
        [NotMapped]
        public string Trigger_DIE_TRG_AU_OF_COB_JURIDICO { get; set; } = `{"triggering_event":"UPDATE","trigger_body":"declare\n\n  VC_OK           varchar2(3) := null;\n  VN_IND_OPERACAO number(1);\n\n  cursor CCartorio is\n    select *\n      from beg_cob_cartorio c\n     where c.beg_cob_cartorio_id = :new.beg_cob_cartorio_id;\n  rcartorio ccartorio%rowtype;\n\n  pragma autonomous_transaction;\n\nbegin\n\n  if NVL(TRUNC(:new.DT_PROCESSO), TRUNC(sysdate - 1)) <>\n     NVL(TRUNC(:old.DT_PROCESSO), TRUNC(sysdate)) then\n    if NVL(:new.NRO_PROCESSO, '^') = NVL(:old.NRO_PROCESSO, '^') then\n      RAISE_APPLICATION_ERROR(-20001,\n                              'Faltou informar o numero do processo');\n    end if;\n  end if;\n\n  if NVL(:new.DT_PROCESSO, TRUNC(sysdate - 1)) <>\n     NVL(:old.DT_PROCESSO, TRUNC(sysdate)) and\n     NVL(:new.NRO_PROCESSO, '^') <> NVL(:old.NRO_PROCESSO, '^') and\n     NVL(:new.DT_BAIXA_JURIDICO, TRUNC(sysdate)) <>\n     NVL(:old.DT_BAIXA_JURIDICO, TRUNC(sysdate)) then\n    RAISE_APPLICATION_ERROR(-20003,\n                            'Não pode ser informado a data de saida neste momento');\n  end if;\n\n  VN_IND_OPERACAO := 1;\n  if NVL(:new.DT_BAIXA_JURIDICO, TRUNC(sysdate + 1)) <>\n     NVL(:old.DT_BAIXA_JURIDICO, TRUNC(sysdate + 1)) then\n    VN_IND_OPERACAO := 3;\n  end if;\n\n  --  RAISE_APPLICATION_ERROR(-20003, 'Passou');\n\n  open ccartorio;\n  fetch ccartorio\n    into rcartorio;\n  close ccartorio;\n\n  VC_OK := DIE_FNC_CRIA_RESTRICAO('J', -- ptipo - Juridico\n                                  VN_IND_OPERACAO, -- pind_operacao\n                                  :new.AD_CLIENT_ID,\n                                  :new.AD_ORG_ID,\n                                  rcartorio.BEG_VW_CLIENTE_ID,\n                                  rcartorio.BEG_CRC_TITULO_ID,\n                                  :new.BEG_COB_JURIDICO_ID, -- porigem_id\n                                  rcartorio.TP_DOCUMENTO, --PTIPODOC,\n                                  rcartorio.TITULO_PARCELA, -- pnrodoc\n                                  rcartorio.BEG_AGENCIA_ID,\n                                  :new.BEG_MOTIVO_BAIXA_ID,\n                                  :new.dt_processo,\n                                  :new.dt_baixa_juridico);\n  if VC_OK = 'OK' then\n    commit;\n  end if;\n\n  if VC_OK <> 'OK' then\n    RAISE_APPLICATION_ERROR(-20010,\n                            'Ocorreu algum erro na criacao da restricao!');\n  end if;\n\nend DIE_TRG_AU_OF_COB_JURIDICO;\n"}`;
    
        [NotMapped]
        public string Trigger_BEG_TRG_BIUD_COB_JURIDICO { get; set; } = `{"triggering_event":"INSERT OR UPDATE OR DELETE","trigger_body":"declare\n  -- local variables here\n/*  cursor CCARTORIO is\n    select *\n      from BEG_COB_CARTORIO X\n     where X.BEG_COB_CARTORIO_ID = :new.BEG_COB_CARTORIO_ID;\n  RCARTORIO CCARTORIO%rowtype;*/\n\nbegin\n\n  -- Se existir dados cartorio\n/*  if INSERTING\n     or UPDATING then\n    if NVL(:new.BEG_COB_CARTORIO_ID, 0) > 0 then\n      open CCARTORIO;\n      fetch CCARTORIO\n        into RCARTORIO;\n      if CCARTORIO%notfound then\n        RAISE_APPLICATION_ERROR(-20002,\n                                'Informações de cartório inexistente!');\n      else\n        :new.AD_ORG_ID         := RCARTORIO.AD_ORG_ID;\n        :new.TP_DOCUMENTO      := RCARTORIO.TP_DOCUMENTO;\n        :new.BEG_VW_CLIENTE_ID := RCARTORIO.BEG_VW_CLIENTE_ID;\n        :new.DT_EMISSAO        := RCARTORIO.DT_EMISSAO;\n        :new.DT_VCTO           := RCARTORIO.DT_VCTO;\n        :new.VLR_TITULO        := RCARTORIO.VLR_TITULO;\n        :new.TITULO_PARCELA    := RCARTORIO.TITULO_PARCELA;\n        :new.BEG_CRC_TITULO_ID := RCARTORIO.BEG_CRC_TITULO_ID;\n        :new.BEG_BANCO_ID      := RCARTORIO.BEG_BANCO_ID;\n        :new.BEG_AGENCIA_ID    := RCARTORIO.BEG_AGENCIA_ID;\n      end if;\n    end if;\n  end if;*/\n\n  -- Quando a trigger for diferente de delete\n  if not DELETING then\n  \n    -- Verifica filial\n    if NVL(:new.AD_ORG_ID, 0) = 0 then\n      RAISE_APPLICATION_ERROR(-20001, 'Deve ser selecionada uma filial!');\n    end if;\n  \n/*    -- Quando existir a informacao do titulo, buscar a data de emissao\n    if NVL(:new.BEG_CRC_TITULO_ID, 0) > 0\n       and :new.DT_EMISSAO is null then\n      select T.DT_EMISSAO\n        into :new.DT_EMISSAO\n        from BEG_CRC_TITULO T\n       where T.BEG_CRC_TITULO_ID = :new.BEG_CRC_TITULO_ID;\n    end if;*/\n  \n  end if;\n\nend BEG_TRG_BIUD_COB_JURIDICO;\n"}`;
    
    }
}
